name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: laravel_test_db
          mysql user: laravel_test_user
          mysql password: super_secret
      - name: Copy .env
        run: cp .env.example .env
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache
      - name: Run Unit tests
        env:
          APP_ENV: local
          DB_CONNECTION: mysql
          DB_USERNAME: laravel_test_user
          DB_PASSWORD: super_secret
          DB_DATABASE: laravel_test_db
        run: |
          php artisan migrate
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          script_stop: false
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/vergecad.info/vergecad-staging/
            git checkout -f
            git add -A .; git stash
            git pull
            /opt/cpanel/composer/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            php artisan config:clear
            mkdir -p /home/${{ secrets.SSH_USERNAME }}/vergecad.info/vergecad-staging/storage/framework/cache/data
            php artisan cache:clear
            php artisan key:generate
            php artisan migrate
            chmod 755 -R storage bootstrap/cache
